=== nightingal3/llm-pretraining-behaviours/metadata/model_metadata_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "author": {
            "type": "string"
        },
        "sha": {
            "type": "string"
        },
        "created_at": {
            "type": "string",
            "format": "date-time"
        },
        "last_modified": {
            "type": "string",
            "format": "date-time"
        },
        "private": {
            "type": "boolean"
        },
        "gated": {
            "type": "boolean"
        },
        "disabled": {
            "type": "boolean"
        },
        "downloads": {
            "type": "integer"
        },
        "likes": {
            "type": "integer"
        },
        "library_name": {
            "type": "string"
        },
        "tags": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "pipeline_tag": {
            "type": "string"
        },
        "mask_token": {
            "type": [
                "string",
                "null"
            ]
        },
        "card_data": {
            "type": "object"
        },
        "widget_data": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "text": {
                        "type": "string"
                    }
                },
                "required": [
                    "text"
                ],
                "additionalProperties": false
            }
        },
        "model_index": {
            "type": [
                "string",
                "null"
            ]
        },
        "config": {
            "type": "object",
            "properties": {
                "architectures": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "model_type": {
                    "type": "string"
                },
                "tokenizer_config": {
                    "type": "object"
                }
            },
            "required": [
                "architectures",
                "model_type",
                "tokenizer_config"
            ],
            "additionalProperties": false
        },
        "transformers_info": {
            "type": "object",
            "properties": {
                "auto_model": {
                    "type": "string"
                },
                "custom_class": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "pipeline_tag": {
                    "type": "string"
                },
                "processor": {
                    "type": "string"
                }
            },
            "required": [
                "auto_model",
                "custom_class",
                "pipeline_tag",
                "processor"
            ],
            "additionalProperties": false
        },
        "safetensors": {
            "type": "object",
            "properties": {
                "parameters": {
                    "type": "object",
                    "patternProperties": {
                        "^[A-Z0-9]+$": {
                            "type": "integer"
                        }
                    },
                    "additionalProperties": false
                },
                "total": {
                    "type": "integer"
                }
            },
            "required": [
                "parameters",
                "total"
            ],
            "additionalProperties": false
        }
    },
    "required": [
        "id",
        "author",
        "sha",
        "created_at",
        "last_modified",
        "private",
        "gated",
        "disabled",
        "downloads",
        "likes",
        "library_name",
        "tags",
        "pipeline_tag",
        "mask_token",
        "card_data",
        "widget_data",
        "model_index",
        "config",
        "transformers_info",
        "safetensors"
    ],
    "additionalProperties": false
}

=== nightingal3/llm-pretraining-behaviours/metadata/model_metadata/NousResearch_Nous-Hermes-2-Yi-34B.json
{
    "id": "NousResearch/Nous-Hermes-2-Yi-34B",
    "author": "NousResearch",
    "sha": "fcb0a8847e76aea14aba9aa44009d4418ad7c18f",
    "created_at": "2023-12-23T19:47:48+00:00",
    "last_modified": "2024-02-20T09:17:20+00:00",
    "private": false,
    "gated": false,
    "disabled": false,
    "downloads": 69617,
    "likes": 225,
    "library_name": "transformers",
    "tags": [
        "transformers",
        "safetensors",
        "llama",
        "text-generation",
        "yi",
        "instruct",
        "finetune",
        "chatml",
        "gpt4",
        "synthetic data",
        "distillation",
        "conversational",
        "en",
        "dataset:teknium/OpenHermes-2.5",
        "base_model:01-ai/Yi-34B",
        "license:apache-2.0",
        "autotrain_compatible",
        "endpoints_compatible",
        "has_space",
        "text-generation-inference",
        "region:us"
    ],
    "pipeline_tag": "text-generation",
    "mask_token": null,
    "card_data": {},
    "widget_data": [
        {
            "text": "Hey my name is Julien! How are you?"
        },
        {
            "text": "Hey my name is Thomas! How are you?"
        },
        {
            "text": "Hey my name is Mariama! How are you?"
        },
        {
            "text": "Hey my name is Clara! How are you?"
        },
        {
            "text": "Hey my name is Julien! How are you?"
        },
        {
            "text": "Hi."
        }
    ],
    "model_index": [
        {
            "name": "Nous-Hermes-2-Yi-34B",
            "results": []
        }
    ],
    "config": {
        "architectures": [
            "LlamaForCausalLM"
        ],
        "model_type": "llama",
        "tokenizer_config": {
            "bos_token": "<|startoftext|>",
            "eos_token": "<|im_end|>",
            "pad_token": "<unk>",
            "chat_template": "{% for message in messages %}{{'<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant\n' }}{% endif %}",
            "unk_token": "<unk>",
            "use_default_system_prompt": false
        }
    },
    "transformers_info": {
        "auto_model": "AutoModelForCausalLM",
        "custom_class": null,
        "pipeline_tag": "text-generation",
        "processor": "AutoTokenizer"
    },
    "safetensors": {
        "parameters": {
            "BF16": 34388917248
        },
        "total": 34388917248
    }
}
